apiVersion: v1
kind: Service
metadata:
  name: gint-redis-service
spec:
  selector:
    app: gint-redis
  ports:
    - protocol: TCP
      port: 6710
      targetPort: 6379
      nodePort: 30009
  type: NodePort

  