// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"ibook/internal/conf"
	"ibook/internal/data"
	"ibook/internal/service"
	"ibook/internal/web"
)

// Injectors from wire.go:

// wireApp init gin application.
func wireApp(secret *conf.Secret, mySQL *conf.MySQL, redis *conf.Redis, server *conf.Server) (*gin.Engine, func(), error) {
	db := data.NewMDB(mySQL)
	client := data.NewRDB(redis)
	dataData := data.NewData(db, client)
	userRepo := data.NewUserRepo(dataData)
	userService := service.NewUserService(userRepo)
	userHandler := web.NewUserHandler(userService)
	v := newMiddleware(secret, client)
	engine := newApp(userHandler, v)
	return engine, func() {
	}, nil
}
