apiVersion: v1
kind: Service
metadata:
  name: gint-mysql-service
spec:
  selector:
    app: gint-mysql
  ports:
    - protocol: TCP
      port: 3309
      targetPort: 3306
      nodePort: 30006
  type: NodePort

  