apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-1gb
spec:
  storageClassName: mysql-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

  