services:
  redis:
    container_name: ibookRedis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  mysql:
    container_name: ibookMysql
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qq781201407
      MYSQL_DATABASE: ibook