server:
  port: :6000
  domain: bswater.cn
data:
  mysql:
    dsn: root:qq781201407@tcp(127.0.0.1:3306)/ibook
  redis:
    addr: redis://127.0.0.1:6379
secret:
  jwt:
    key: "bswaterb12345678"
    life_duration_time: 43200